# Site settings
title: Hussein Taher | Programmer
description: > # A little description
 Hussein Taher, I'm a programmer. Interested in
 games, websites, networking, databases, 2d, art, graphics, 3d modelling.
 blog about game development programming algorithms projects javascript js c++ css html5
baseurl: ""
url: "http://husenap.github.io"
github_username: Husenap

disqus_shortname: husenap

theme1: "#000"
theme2: "#212121"
theme3: "#303030"
theme4: "#424242"
color500: "#9C27B0"
color700: "#7B1FA2"
color800: "#6A1B9A"
accent200: "#69F0AE"
accent400: "#00C853"
shade: "#263238"
addressbar: "#7B1FA2"

text: "#fff"
primary-text: 1
secondary-text: 0.7
hint-text: 0.5
divider: 0.12

# Build settings
markdown: kramdown
